//
// Created by Yotam Manne on 23/07/2018.
//

#include "Exceptions.h"
enum Exception{
    NO_ERROR,
    MEMORY_ALLOC_ERROR,
    INVALID_COMMAND_ERROR,
    CELL_FIXED_ERROR,
    SOLVE_IO_ERROR,
    EDIT_IO_ERROR,
    BINARY_RANGE_ERROR,
    VALUE_RANGE_ERROR,
    ERRONEOUS_BOARD_ERROR,
    BOARD_NOT_EMPTY_ERROR,
    GENERATOR_FAILED_ERROR,
    UNDO_ERROR,
    REDO_ERROR,
    VALIDATION_FAILED_ERROR,
    SAVE_IO_ERROR,
    CELL_HAS_VALUE_ERROR,
    BOARD_UNSOLVEABLE_ERROR,
    ILP_ERROR
};

